### ISSUE TITLE
Expand on "what does it mean for an incentive to have multiple amounts?"

### ISSUE THREAD

**Issue by FredericoAndrade** [NODE-Collective/specification#4]
https://github.com/NODE-Collective/specification/blob/1e5595660f329a6259f4f7e27f43cff2e39d4e4e/SPECIFICATION.md?plain=1#L89

**Comment by kswb** [comment]
Questions for whoever takes this:

What is considered an 'amount' that is distinct from another?

- For example, would we consider a $100 rebate for an EV charger amount_1, and a 'bonus' rebate for low-income buyers of another $100 to be amount_2? Or, would this be multiple incentives under a single program?

**Comment by mpusto** [comment]
Good question @kswb. When Rewiring America has had these types of incentives, we have determined that these are two separate incentives. We ask ourselves "Can everyone apply for the incentive entered in a single incentive?”. So if not everyone gets that incentive, then we have a separate line for the low income program. In our data, we link that to a table with various low-income thresholds. You'll see in the spec that there is an `income_qualified` attribute for the amount table. There is also a boolean on the Incentive table for `income_qualified`. A single incentive MUST have a true/false in that field, so a single incentive cannot be both a low-income incentive and a market-rate incentive.

Multiple amounts in this case is referring to situations where you may have a cap--like "$1.50/sq ft for insulation, up to $2000". The first amount row would be the $1.50/sq ft, while the second row would be the max value. These are for the same Incentive. Or an incentive where the amount is "50% of the project cost, up to $4,000." The 50% and the $4,000 are separate amount lines of the same incentive.

And now I've convinced myself to just assign myself the Issue. 😂
