### ISSUE TITLE
Expand on geography_type > Municipality and Utility Service Territory 

### ISSUE THREAD

**Issue by FredericoAndrade** [NODE-Collective/specification#6]
https://github.com/NODE-Collective/specification/blob/1e5595660f329a6259f4f7e27f43cff2e39d4e4e/SPECIFICATION.md?plain=1#L176

**Comment by kswb** [comment]
Friendly ping to remind of the notes from last week, @oyamauchi, on possibly sharing some knowledge about helping describe and identify boundaries here and/or within RA. I'm happy to share knowledge within this thread if that's useful.
